### ISSUE TITLE
exome-seq: results output organization and file changes

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-cwl#20]
The results output directories should be organized by step:

- results/
  - final indels/snp genotype vcf file
  - QC report(s)
  - gvcfs/
  - bams-markduplicates/
    - individual bam and bai files from markduplicates
  - bams-final/
    - individual bam and bai files from HaplotypeCaller
  - documentation
    - README
    - logs/
    - scripts/

Files to include:

- BAMs from MarkDuplicates (these are currently dropped)
- Final bams from HaplotypeCaller (These are not currently generated, but there is an option on HaplotypeCaller to produce them)

Files to exclude:

- recalibrated bams and recalibration tables

**Comment by dleehr** [comment]
Part of this needs to be done by lando, since the cwl workflow has no control over the documentation or logs/scripts

**Comment by dleehr** [comment]
Need to clarify if the QC reports are multiple, a directory, a zip file, or a single file.

**Comment by johnbradley** [comment]
One approach where you can dynamically build the directory structure via a tool: https://www.biostars.org/p/240726/
Based on a simple test it looks like you don't end up with named outputs. Only the directory gets a name.
```
   "variant_recalibration_snps_recal": [...
"basename": "SRR099967-raw_variants.g.vcf", 
...
   ],
 "variant_recalibration_snps_recal": {...
"basename": "testproj-snps_vqsr_recal.out",
```
vs
```
"gvcfs": {...
        "basename": "gvcfs", 
        "listing": [
            {...
                "basename": "SRR099967-raw_variants.g.vcf", 
            }, 
            {...
                "basename": "testproj-snps_vqsr_recal.out", 
            }
             ...
        ], 
...
    }
```

**Comment by dleehr** [comment]
> Based on a simple test it looks like you don't end up with named outputs. Only the directory gets a name.

I see. I thought we could simply change the output file name though. Maybe the tool interface isn't smart enough to handle that though.
