### ISSUE TITLE
exome-seq: Correct output type for hs_metrics_dir

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/bespin-cwl#29]
hs_metrics_dir type should be `Directory` not `File`.
https://github.com/Duke-GCB/bespin-cwl/blob/a828902416018c2523903d9ffa78ae0a14d8a3ee/workflows/exomeseq.cwl#L79-L81

**Comment by dleehr** [comment]
I cherry picked the fix for this in 73463250ee493ce667c2ec48bed28863865c000b, didn't know if a PR for the other branch was imminent
