### ISSUE TITLE
Generate packed workflows using CI and upload as GitHub release

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-cwl#44]
Generating packed workflows manually can be error-prone and can easily be disconnected from the master branch.

It's a good practice to tag releases for versioning, and with that we can use CI to build the packed workflows when new tags are pushed. Uploading packed workflows to a GitHub release will also give them cleaner URLs, like we do in [bespin-ui](https://github.com/Duke-GCB/bespin-ui/blob/master/.travis.yml#L16)

**Comment by hlapp** [comment]
👍
