### ISSUE TITLE
exome seq: missing index after picard-MarkDuplicates

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/bespin-cwl#7]
I had an where cwltool was missing a '.bai' index for a bam file.
Adding `CREATE_INDEX=True` to `tools/picard-MarkDuplicates.cwl` fixed this error.
This might be due to a change in the docker file related to 'tools/picard-MarkDuplicates.cwl'.

**Comment by dleehr** [comment]
Looks like this was fixed by 55addf43e5cd9a4b2bcdbf95430ecdffdfcb7281, is that true?

**Comment by johnbradley** [comment]
You are correct.
